### PR TITLE
Update library_materialdialogs_strings.xml

### PR DESCRIPTION
**Pull request by MSF-Jarvis**

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you for the PR. 

Could you also please add the custom variables:
https://github.com/mikepenz/AboutLibraries/blob/742af897d06987e26f5903545dec0446b50b4886/library/src/main/res/values/library_caldroid_strings.xml#L17

And the "year;owner" definition inside the define tag. 
https://github.com/mikepenz/AboutLibraries/blob/742af897d06987e26f5903545dec0446b50b4886/library/src/main/res/values/library_caldroid_strings.xml#L4

so the placeholders are replaced for the MIT license?

**Comment by MSF-Jarvis** [comment]
Sure, five minutes please :)

**Comment by mikepenz** [comment]
No hurry. I will merge later today, when I am at home

**Comment by MSF-Jarvis** [comment]
Done, should be mergeable now :smiley:

**Comment by mikepenz** [comment]
@MSF-Jarvis thanky ou

**Comment by MSF-Jarvis** [comment]
I'll be sending more of them in a couple of days, need to add in some of
the libraries I'm using in my projects.

**Comment by mikepenz** [comment]
thank you

**Pull request merged**
