### PR TITLE
new Library AndroidWeekView

### PR DESCRIPTION
**Pull request by rafi0101**
Added this Library:
https://github.com/thellmund/Android-Week-View

### CODE REVIEW

**Comment by mikepenz** [comment]
@rafi0101 thank you for the PR. but starting with v8 of the AboutLibraries this is no longer necessary :) 

The gradle plugin will make sure to pull the relevant information from the POM file. 

If there is some information not properly maintained by that library in the POM file it would be interesting which particular thing is missing / what needs adjustment

**Comment by rafi0101** [comment]
@mikepenz ok.
The library is not shown in the app, and I thought this is still the way to add it.


did I do something wrong?
I've added the following line to my app: build.gradle:

`implementation 'com.github.thellmund.Android-Week-View:core:4.1.6'`

Used the Library in my app, run gradle build and launched the app.

**Comment by mikepenz** [comment]
Do you see the library using:

```
./gradlew exportLibraries
or
./gradlew findLibraries
```
?

Perhaps you need to do a clean build. there is strong caching built in to keep your builds fast :)

**Comment by Renealpha** [comment]
Buenos días te comento que no hablo inglés desconozco la serie de correos
electrónicos que me han enviado con respecto a que sean puedo colaborar de
alguna manera en Android o con respecto a la programación cosa que no
entiendo a qué se refiere el contenido y el acceso a la aplicación en
referencia por lo que agradeceré me lo pueden explicar y de qué manera
puedo colaborar.

**Comment by rafi0101** [comment]
@mikepenz thanks for the quick response. Now i see the Library in my app :)

> Do you see the library using:
>
>`./gradlew exportLibraries`
>`or`
>`./gradlew findLibraries`

The Library is listed in both lists.
After cleaning an rebuilding the project, it worked for me.

I've been using this library for several days now, and didn't thought it would be cached that long

**Pull request closed without merging**
