### PR TITLE
Allow excluding dependencies at build time

### PR DESCRIPTION
**Pull request by mgray88**
- Mapping file defines an id to map to another id to merge with

### CODE REVIEW

**Comment by mgray88** [comment]
This is probably not the best way to do this, however I wanted to get the PR started. I am no gradle expert so I'm having trouble getting the app to use the locally built plugin.

**Comment by mikepenz** [comment]
oh I am also not a gradle expert. what I usually do: 

1.) change the version in `plugin/build.gradle` to a higher version
2.) use `uploadArchives` to install it locally (see picture below)
3.) use the new version in the global `build.gradle` for the plugin

This usually works for me :) 

image

**Comment by mgray88** [comment]
Thinking about this a little more, merging dependencies would essentially be excluding them, as merging a child dependency into a parent dependency means you don't really care about the child dependency info right? I think essentially what I'm going to do is add an exclusion list config file and skip the dependencies in that file

**Comment by mikepenz** [comment]
@mgray88 I think for a first version that is sufficient. 

for the merging part. I believe that kind of overlaps with the multi license per library feature. as merging may also mean there are different libraries in the too-be-merged libraries. or other fields which may differ based on the modules

**Comment by mgray88** [comment]
True. I'm not sure how easy it would be to handle that automatically though, it seems more like something that falls under your disclaimer `Careful optimisation and review of all licenses` :)

**Comment by mikepenz** [comment]
Thanks again a lot for this PR :)

**Pull request merged**
