### PR TITLE
Added magister.java

### PR DESCRIPTION
**Pull request by iLexiconn**

### CODE REVIEW

**Comment by mikepenz** [comment]
@iLexiconn you are the author of that lib?

**Comment by iLexiconn** [comment]
Yes I am. :)

**Comment by mikepenz** [comment]
@iLexiconn you can also add this definition file to your library, so it will automatically show up for people using the `AboutLibraries`. I do the same for my libs:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/library_materialdrawer_strings.xml

just change ** define_int_magisterjava** to ** define_magisterjava**

**Comment by iLexiconn** [comment]
The library is not made in an Android development environment, so I can't do it that way.

**Comment by mikepenz** [comment]
ah ok i see. then thanks for your contribution. will be in the next version

**Comment by iLexiconn** [comment]
:)

**Pull request merged**
