### PR TITLE
2 new Libraries

### PR DESCRIPTION
**Pull request by RubenGees**
Added these Libraries I use in my Project:
https://github.com/lecho/hellocharts-android
https://github.com/ApmeM/android-flowlayout

### CODE REVIEW

**Comment by mikepenz** [comment]
@RubenGees thanks

**Comment by RubenGees** [comment]
Those Libraries don't show up. Any idea why?

**Comment by mikepenz** [comment]
@RubenGees yeah i just saw that you set the classPath value wrong, so it won't automatically show up. 

The classPath value should be a specific class which is inside the library. Like org.apmem.tools.layouts.FlowLayout for the android-flowlayout library

**Comment by RubenGees** [comment]
Can it be any random class from the lib?

**Comment by mikepenz** [comment]
@RubenGees it can be. but should one which is one of the Main classes so the chance is very low that it will be removed

**Pull request merged**
