### PR TITLE
Dbflow 4.0.4 -> 4.0.5

### PR DESCRIPTION
**Pull request by AllanWang**
PS. I typically edit the versions directly on github so there's one new commit per file change. If you'd like, you can use squash and merge rather than just merge so that only one commit is added rather than all my commits plus a merge commit.

### CODE REVIEW

**Comment by mikepenz** [comment]
@AllanWang why is there a merge conflict necessary? Can't you just sync your develop with mine (by pulling from my remote) prior to doing changes? Otherwise you might want to fork newly :D

**Comment by AllanWang** [comment]
Is there a merge conflict? I just synced my repo with yours. But when doing that on github it generates a commit for that. There still shouldn't be a conflict though

**Comment by mikepenz** [comment]
@AllanWang no, no conflict :D just mentioned it as the commit and branch graph will look funny :D

**Comment by AllanWang** [comment]
Look funny when squashing or because of my first merge commit? If it's the latter, I agree. I usually delete my fork and fork again to avoid that, but if you squash everything it might have made it look nicer.

**Comment by mikepenz** [comment]
Ah don't worry. It's fine :) thank you very much

**Pull request merged**
