### PR TITLE
Create library_jmdns.xml

### PR DESCRIPTION
**Pull request by mueller-ma**
How do I get the classPath?

### CODE REVIEW

**Comment by mikepenz** [comment]
@mueller-ma the class path is one of the main classes of the library. basically packagename + class name (sadly java does not allow to check for the existence of a package)

**Comment by mueller-ma** [comment]
@kaikreuzer What's the classpath of the jmdns library? `javax.jmdns.JmDNS`?

**Comment by mikepenz** [comment]
@mueller-ma exactly :)

**Comment by kaikreuzer** [comment]
Right, [here's the proof](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/JmDNS.java) ;-)

**Comment by mueller-ma** [comment]
I'm sorry, I wanted to ping the maintainer with my comment, but github removed the ping. Probably I misspelled it.

@kaikreuzer What's the classpath of the jmdns library? javax.jmdns.JmDNS ?

**Comment by kaikreuzer** [comment]
@mueller-ma, I assume you didn't yet see https://github.com/mikepenz/AboutLibraries/pull/380#issuecomment-375196892, right?

**Comment by mikepenz** [comment]
@kaikreuzer @mueller-ma thank you both!

**Pull request merged**
