### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by androideveloper**
added new app, that uses this library

### CODE REVIEW

**Comment by mikepenz** [comment]
@androideveloper sorry I can'T merge this as it has many more commits included than necessary. How have you done the PR?

**Comment by mikepenz** [comment]
Please also tell me where I can find the MaterialDrawer and the AboutLibraries used in this app. Downloaded it and can'T find it?

**Comment by androideveloper** [comment]
@mikepenz I have edited Read.me file and it automatically forked the project. After that I have sent pull request. If there are problems with pull request, can you please add our app line to read.me? About the app: MiniDrawer used for the main menu is from MaterialDrawer library. Open Settings -> About -> overflow icon. And you can find open source licenses there.

**Comment by 7172** [comment]
Ok sure but till now my pc not work properly
--
Sent from myMail app for Android Thursday, 14 July 2016, 07:22p.m. +08:00 from Roland  notifications@github.com :

**Comment by mikepenz** [comment]
@androideveloper seems like you had an old fork or so because the pr contains many commits from the past. I will close it and add the app manually in this case

**Pull request closed without merging**
