### PR TITLE
Add Library VNTNumberPickerPreference

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by mikepenz** [comment]
@vanniktech those are your libraries. right? you can also include the definition file directly within your lib. As done in my libs: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/library_materialdrawer_strings.xml

**Comment by vanniktech** [comment]
@mikepenz yup they are my libraries. Thanks for the advice. I just pushed it with https://github.com/vanniktech/VNTNumberPickerPreference/commit/7c2736f5b42a32e30becca1dd58dd8efa35a5391

**Comment by mikepenz** [comment]
Your have to remove _int from the first line define string.

Niklas Baudy <notifications@github.com> schrieb am Fr., 18. Sep. 2015 08:25:

**Comment by mikepenz** [comment]
Take a look at the sample of the MaterialDrawer I sent

Mike Penz <mikepenz@gmail.com> schrieb am Fr., 18. Sep. 2015 08:30:

**Comment by vanniktech** [comment]
Thanks.

Fixed with https://github.com/vanniktech/VNTNumberPickerPreference/commit/c43f974c4f49e96e423026f692a0537226fdfad2

**Pull request closed without merging**
