### PR TITLE
10 new libraries

### PR DESCRIPTION
**Pull request by JordanGout**
Hope everything is correct.

### CODE REVIEW

**Comment by mikepenz** [comment]
@JordanGout it seems fine. Just one thing. The classpaths you have defined should point to an class which can be instantiated. Else it's not really easy for the lib to make sure a specific lib exists. (I use this to see if the class which is written can be found and if yes i'll automatically add the lib) 

Can you please change it to point to a real class? I will do a quick check on something i just had in mind. i'll let you know if it worked ;)

**Comment by mikepenz** [comment]
@JordanGout ok the idea i had seems to be not possible. :/

**Comment by JordanGout** [comment]
I've changed the classpaths to a real class.

I also changed the classpaths of crashlytics and facebook because there are out of date.

**Comment by mikepenz** [comment]
@JordanGout looks great :) thank you

**Comment by vanniktech** [comment]
Hmm I can't find the `com.facebook.FacebookSdk` class. I'm using `'com.facebook.android:facebook-android-sdk:3.22.0'` Is `FacebookSdk` only present in 4 and above?

**Comment by mikepenz** [comment]
@vanniktech if the auto detection does not work you can also just enable it via the builder. `withLibraries("facebook")` perhaps the classpath is wrong and should be changed? you can open a pull request if you like to ;)

**Comment by vanniktech** [comment]
I found one issue, you'll get a PR in a few moments.

**Pull request merged**
