### PR TITLE
Create library_permissionsdispatcher_strings.xml

### PR DESCRIPTION
**Pull request by kalyandechiraju**
Add [PermissionsDispatcher](https://github.com/hotchemi/PermissionsDispatcher) Library definitions.

### CODE REVIEW

**Comment by tomh12389** [comment]
On Jan 31, 2017 3:20 PM, "Kalyan Dechiraju" <notifications@github.com>
wrote:

Add PermissionsDispatcher Library definitions.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/mikepenz/AboutLibraries/pull/292
Commit Summary

   - Create library_permissionsdispatcher_strings.xml

File Changes

   - *A* library/src/main/res/values/library_permissionsdispatcher_
   strings.xml
   <https://github.com/mikepenz/AboutLibraries/pull/292/files#diff-0> (21)

Patch Links:

   - https://github.com/mikepenz/AboutLibraries/pull/292.patch
   - https://github.com/mikepenz/AboutLibraries/pull/292.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mikepenz/AboutLibraries/pull/292>, or mute the thread

**Comment by mikepenz** [comment]
@kalyandechiraju please fix the PR:
`Apostrophe not preceded by \`

**Comment by mikepenz** [comment]
@kalyandechiraju oh sorry seems not to be related to your PR

**Comment by kalyandechiraju** [comment]
Yes, noticed that.

**Pull request merged**
