### PR TITLE
Added 3 new libs and updated 1

### PR DESCRIPTION
**Pull request by jaredsburrows**
PR for https://github.com/mikepenz/AboutLibraries/issues/201

**Add new:**
```
compile 'com.github.paolorotolo:appintro:3.4.0'
compile 'com.annimon:stream:1.0.8'    
compile 'com.pixplicity.easyprefs:library:1.8.1@aar'
```

**Will update:**
```
compile 'com.google.android.gms:play-services-gcm:8.4.0' 
```

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@mikepenz Since `play-services-gcm` and all other GPS libraries are close source, should we create a separate libs XML for each one?

**Comment by mikepenz** [comment]
@jaredsburrows I think it's fine if there's only one for the complete package

**Comment by jaredsburrows** [comment]
@mikepenz Ok. That's fine.

**Comment by jaredsburrows** [comment]
@mikepenz After this PR, can you make a release?

**Comment by mikepenz** [comment]
v5.6.1

**Pull request merged**
