### PR TITLE
Added sample class for Jetpack Navigation

### LINKED ISSUE #530: What is the recommended way to use this library with Jetpack navigation?
## About this issue
What is the recommended way to use this library with Jetpack navigation? I couldn't find anything about it on the README.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

### PR DESCRIPTION
**Pull request by yashx**
closes #530

### CODE REVIEW

**Comment by mikepenz** [comment]
@yashx thank you so much. the failure is not related to your chnages I believe. will have a look

**Comment by mikepenz** [comment]
I merged this. but for some reason it didn't register it. thanks so much for the PR

**Comment by yashx** [comment]
@mikepenz  I don't think this was merged. NavHostDestinationFragment.kt the file in which I gave the example is not present in https://github.com/mikepenz/AboutLibraries/tree/develop/app/src/main/java/com/mikepenz/aboutlibraries/sample
And this is still private.
https://github.com/mikepenz/AboutLibraries/blob/5c5d20308af0fcd3fbabef79c4a733463d2d6726/library/src/main/java/com/mikepenz/aboutlibraries/ui/LibsSupportFragment.kt#L16

**Comment by mikepenz** [comment]
Oh I see where I did wrong. It merged it into: https://github.com/mikepenz/AboutLibraries/pull/534/ this PR. 
It will get into a new release as soon as the plugin get's approved on Gradle Plugin Repo. Really hope this happens soon

**Pull request closed without merging**
